#!/usr/bin/env python3
"""Derive the userspace-relevant part of the Steam Frame kernel config.

Usage: gen-frame-fragment.py <kernel-source-dir> <frame-kernel.config> > 10-frame-userspace.config

The Frame kernel (linux-618-deckard 6.18.0, IKCONFIG of work/frame/frame-Image) is a
Snapdragon SoC kernel. A VM can use its generic options (scheduler, cgroups, mm, fs,
net, crypto, security, ...) but none of its SoC/board drivers. Every Frame symbol is
classified by the Kconfig file that defines it in the target kernel source:

* generic directories (GENERIC_DIRS): Frame's value is copied verbatim, including
  "is not set", so the userspace-visible feature set (and every choice: preemption
  model, LSM order, compression defaults, ...) matches the Frame.
* virtual/protocol driver directories (DRIVER_DIRS): only enabled options are copied;
  "is not set" lines are dropped so they cannot switch off the VM drivers enabled by
  the libkrunfw base (e.g. Frame has "# CONFIG_VIRTIO_BLK is not set").
* everything else (SoC, buses, PCI/USB/I2C/SPI, media, sound/soc, wireless,
  bluetooth, power, thermal, KVM host, ...) is dropped.

Output is reviewed and committed as config/10-frame-userspace.config;
config/20-steamac.config has the final word on top of it.
"""
import os
import re
import sys

src, frame_cfg = sys.argv[1], sys.argv[2]

GENERIC_DIRS = (
    "init/", "kernel/", "mm/", "block/", "io_uring/", "ipc/", "lib/", "crypto/",
    "security/", "certs/", "usr/", "fs/", "net/", "arch/Kconfig", "arch/arm64/Kconfig",
    "arch/arm64/Kconfig.debug", "drivers/base/", "drivers/of/",
)
DRIVER_DIRS = (
    "drivers/android/", "drivers/block/", "drivers/md/", "drivers/dma-buf/",
    "drivers/hid/", "drivers/input/", "drivers/net/Kconfig", "drivers/misc/Kconfig",
    "drivers/char/", "drivers/tty/", "drivers/video/", "drivers/gpu/drm/Kconfig",
    "drivers/connector/", "drivers/virtio/", "drivers/dax/", "drivers/rtc/Kconfig",
    "sound/Kconfig", "sound/core/",
)
EXCLUDED_DIRS = (
    "arch/arm64/Kconfig.platforms",   # ARCH_QCOM & co.
    "arch/arm64/kvm/", "virt/",       # KVM host: no nested virtualisation under HVF
    "net/wireless/", "net/mac80211/", "net/bluetooth/", "net/rfkill/", "net/nfc/",
    "net/ieee802154/", "net/mac802154/", "net/6lowpan/", "net/qrtr/", "net/dsa/",
    "net/ncsi/", "net/phonet/", "net/can/",
    "drivers/char/hw_random/",        # SoC RNGs; HW_RANDOM_VIRTIO is set in 20-steamac
    "drivers/char/tpm/",
    "drivers/tty/serial/",            # SoC UARTs; PL011 is set in 20-steamac
    "drivers/input/touchscreen/", "drivers/input/keyboard/", "drivers/input/mouse/",
    "drivers/input/rmi4/", "drivers/input/serio/",
    "drivers/video/backlight/",
)
# Symbols whose Frame values are device/board specific.
DENY = re.compile(
    r"^(KVM.*|HAVE_KVM.*|CMDLINE.*|LOCALVERSION.*|DEFAULT_HOSTNAME|INITRAMFS_.*|"
    r"NR_CPUS|SYSTEM_TRUSTED_KEYS|EXTRA_FIRMWARE.*|ARCH_.*|CC_.*|AS_.*|LD_.*|GCC_.*|"
    r"PAHOLE_VERSION|RUSTC_.*|TOOLS_SUPPORT_.*|BUILDTIME_.*|.*_SUPPORT|HAVE_.*)$"
)

kconfig_rx = re.compile(r"^\s*(?:menu)?config\s+([A-Za-z0-9_]+)\s*$")
defs = {}
for dirpath, _, files in os.walk(src):
    for f in files:
        if f.startswith("Kconfig"):
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, src)
            with open(path, errors="ignore") as fh:
                for line in fh:
                    m = kconfig_rx.match(line)
                    if m:
                        defs.setdefault(m.group(1), set()).add(rel)


def arm64_relevant(path):
    return not path.startswith("arch/") or path.startswith(("arch/arm64/", "arch/Kconfig"))


def classify(sym):
    paths = [p for p in defs.get(sym, ()) if arm64_relevant(p)]
    if not paths:
        return None
    if any(p.startswith(EXCLUDED_DIRS) for p in paths):
        return None
    if any(p.startswith(GENERIC_DIRS) for p in paths):
        return "generic"
    if any(p.startswith(DRIVER_DIRS) for p in paths):
        return "driver"
    return None


set_rx = re.compile(r"^CONFIG_([A-Za-z0-9_]+)=(.*)$")
unset_rx = re.compile(r"^# CONFIG_([A-Za-z0-9_]+) is not set$")
out = []
with open(frame_cfg) as fh:
    for line in fh:
        line = line.rstrip("\n")
        m = set_rx.match(line)
        if m:
            sym, val = m.groups()
            if DENY.match(sym):
                continue
            if classify(sym):
                out.append(line)
            continue
        m = unset_rx.match(line)
        if m and not DENY.match(m.group(1)) and classify(m.group(1)) == "generic":
            out.append(line)

print("# Generated by guest/kernel/tools/gen-frame-fragment.py from the Steam Frame kernel")
print("# config (linux-618-deckard 6.18.0, work/frame/frame-kernel.config). Do not edit;")
print("# put overrides in 20-steamac.config.")
print("\n".join(out))
